name: Build Android APK

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          
      # UPDATED to v5 to support Node 24 and silence the warning
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install flet
          
      - name: Build APK via Flet
        run: flet build apk --yes --verbose
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sales-App-APK
          path: build/apk/**/*.apk
